version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: url-shortener-api
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    env_file:
      - .env
    environment:
      - DEV_REDIS_HOST=redis  # override default redis host
    depends_on:
      - redis
    networks:
      - url-shortener-network
    command: npm run start:dev

  redis:
    image: redis:7-alpine
    container_name: url-shortener-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    networks:
      - url-shortener-network
    command: redis-server --appendonly yes

networks:
  url-shortener-network:
    driver: bridge

volumes:
  redis-data: