FROM node:22-alpine

WORKDIR /home/node/app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy project files
COPY . .

# Expose API port
EXPOSE 8000

# Run the application
CMD ["npm", "run", "start:dev"]